# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
      - id: autopep8
        entry: autopep8
  - repo: local
    # These hooks are run from the local virtual env (and it's assumed they are there)
    # to allow these tools to find project dependencies.
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [ python ]
        args: ['--install-types', '--non-interactive']
