---
default_language_version:
  node: system

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c # 4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-symlinks

  - repo: https://github.com/adrienverge/yamllint
    rev: 81e9f98ffd059efe8aa9c1b1a42e5cce61b640c6 # 1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: f295829140d25717bc79368d3f966fc1f67a824f # 0.41.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: 2491238703a5d3415bb2b7ff11388bf775372f29 # 0.10.0
    hooks:
      - id: shellcheck
        args: ["--severity=info"]

  - repo: https://github.com/rhysd/actionlint
    rev: 62dc61a45fc95efe8c800af7a557ab0b9165d63b # 1.7.1
    hooks:
      - id: actionlint

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: f1ebc5730d98440041cc43e4d69829ad598ae1e7 # 0.6.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: d4911cfb7f1010759fde68da196036feeb25b99d # 1.11.2
    hooks:
      - id: mypy
        args: ['--install-types', '--non-interactive']
        additional_dependencies:
          - "Jinja2>=3.1.2"
          - "PyYAML>=6.0"
        exclude: examples/

  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python -m unittest discover -v -s src/
        additional_dependencies:
          - "Jinja2>=3.1.2"
          - "PyYAML>=6.0"
        language: python
        'types': [python]
        pass_filenames: false
        stages: [pre-commit]
