---
default_language_version:
  node: system

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-symlinks

  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530 # v1.38.0
    hooks:
      - id: yamllint

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 5b5dddc4fb0f83c3ea1fc5616fa63e115dce83e0 # v0.49.1
    hooks:
      - id: markdownlint

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: 99470f5e12208ff0fb17ab81c3c494f7620a1d8d # v0.11.0
    hooks:
      - id: shellcheck
        args: ["--severity=info"]

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
    hooks:
      - id: actionlint

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: f1ebc5730d98440041cc43e4d69829ad598ae1e7 # 0.6.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: d4911cfb7f1010759fde68da196036feeb25b99d # 1.11.2
    hooks:
      - id: mypy
        args: ['--install-types', '--non-interactive']
        additional_dependencies:
          - "Jinja2>=3.1.2"
          - "PyYAML>=6.0"
        exclude: examples/

  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python -m unittest discover -v -s src/
        additional_dependencies:
          - "Jinja2>=3.1.2"
          - "PyYAML>=6.0"
        language: python
        'types': [python]
        pass_filenames: false
        stages: [pre-commit]
