name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install lint dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --editable .
        pip install '.[lint]'
    - name: Analysing the code with ruff
      run: |
        ruff check src/
    - name: Analysing the code with mypy
      run: |
        mypy --install-types --non-interactive src/
