name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install publish dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[publish]'
    - name: Build and test wheel
      run: |
        rm -rf dist/
        python -m build --sdist --wheel .
        twine check dist/*
    - name: Publish
      run: |
        twine upload  --non-interactive --verbose --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} dist/*

