---
name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Package wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
        with:
          python-version: "3.13.0"
      - name: Install publish dependencies
        run: |
          python -m pip install --upgrade pip build
      - name: Build and test wheel
        run: |
          rm -rf dist/
          python -m build --sdist --wheel .
      - name: Store wheel
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882  # v4.4.3
        with:
          name: beku-stackabletech-package
          path: dist/
  pypi-publish:
    name: Upload to PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/beku-stackabletech
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download wheel
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: beku-stackabletech-package
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@15c56dba361d8335944d31a2ecd17d700fc7bcbc # v1.12.2
