name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --editable .
    - name: Run unit tests
      run: |
        python -m unittest discover -v -s src/
